pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
  
      steps {
        sh 'mvn --version'
      }
      
    }
      stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "srinivas922023/ultimate-cicd:${BUILD_NUMBER}"
      
        REGISTRY_CREDENTIALS = credentials('docker-hub')
      }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      
      steps {
        sh 'node --version'
      }
    }
  }
}
